server:
  port: 7070
spring:
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:543/postgres
    username: postgres
    password: postgres
  flyway:
    enabled: false
